export const institutions = {
  "10th": [
    "Kavian",
    "Navodya",
    "Delhi Public School (DPS)",
    "The Doon School",
    "Sardar Patel Vidyalaya",
    "St. Xavier's School",
    "Rashtriya Indian Military College (RIMC)",
    "Army Public School",
    "La Martiniere School",
    "Welham Boys' School",
    "Mallya Aditi International School",
    "Bhartiya Vidya Bhavan",
    "Vasant Valley School",
    "Shri Ram School",
    "Ecole Mondiale World School",
    "Sanskriti School",
    "The Mother's International School",
    "Mount Carmel School",
    "St. Joseph's Boys' School",
    "International School Bangalore (ISB)",
    "Indira Gandhi Memorial School",
    "Ramagya School",
    "Ryan International School",
    "St. Mary's School",
    "Fergusson College School",
    "Siliguri Institute of Technology School",
    "Billabong High International School",
    "Amity International School",
    "Apeejay School",
    "Kendriya Vidyalaya",
    "Vidya Niketan",
    "Springdales School",
    "Vidyashilp Academy",
    "Ramakrishna Mission Vidyalaya",
    "Oxford English School",
    "Jain International Residential School",
    "Bangalore International School",
    "Indraprastha International School",
    "Blue Bells International School",
    "BGS International Public School",
    "St. Xavier's Collegiate School",
    "Other",
  ],
  "12th": [
    "Kavian",
    "Navodya",
    "Delhi Public School (DPS)",
    "The Doon School",
    "Sardar Patel Vidyalaya",
    "St. Xavier's School",
    "Rashtriya Indian Military College (RIMC)",
    "Army Public School",
    "La Martiniere School",
    "Welham Boys' School",
    "Mallya Aditi International School",
    "Bhartiya Vidya Bhavan",
    "Vasant Valley School",
    "Shri Ram School",
    "Ecole Mondiale World School",
    "Sanskriti School",
    "The Mother's International School",
    "Mount Carmel School",
    "St. Joseph's Boys' School",
    "International School Bangalore (ISB)",
    "Indira Gandhi Memorial School",
    "Ramagya School",
    "Ryan International School",
    "St. Mary's School",
    "Fergusson College School",
    "Siliguri Institute of Technology School",
    "Symbiosis International School",
    "Maharashtra Education Society School",
    "Bangalore International School",
    "The International School of Hyderabad",
    "Indus International School",
    "Pathways World School",
    "The British International School",
    "Amity International School",
    "Jain International Residential School",
    "Kendriya Vidyalaya",
    "Billabong High International School",
    "Aditya Birla World Academy",
    "Asian International School",
    "Rajhans Vidyalaya",
    "Podar International School",
    "Mallya Aditi International School",
    "Sardar Patel Vidyalaya",
    "Vidyashilp Academy",
    "Sanskriti School",
    "Mount Carmel School",
    "Indraprastha International School",
    "Vivekanand International School",
    "Bishop Cotton Boys' School",
    "Other",
  ],
  UG: [
    "IIT Bombay",
    "IIT Delhi",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT BHU",
    "NIT Trichy",
    "NIT Surathkal",
    "NIT Warangal",
    "NIT Calicut",
    "VIT Vellore",
    "BITS Pilani",
    "CU Chandigarh",
    "MIT Pune",
    "Amity University",
    "SRM Institute of Science and Technology",
    "Thapar University",
    "Punjab Engineering College",
    "Shiv Nadar University",
    "Manipal Institute of Technology",
    "University of Delhi",
    "Institute of Chemical Technology (ICT Mumbai)",
    "Jamia Millia Islamia",
    "Banaras Hindu University (BHU)",
    "Indian Institute of Engineering Science and Technology (IIEST)",
    "National Institute of Fashion Technology (NIFT)",
    "University of Pune",
    "University of Mumbai",
    "Indian Institute of Management (IIM) Indore",
    "Indian Institute of Management (IIM) Lucknow",
    "Indian Institute of Management (IIM) Ahmedabad",
    "Indian Institute of Management (IIM) Bangalore",
    "National Law University (NLU) Delhi",
    "National Law University (NLU) Jodhpur",
    "Jamia Hamdard University",
    "Dr. B.R. Ambedkar National Institute of Technology (NIT Jalandhar)",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "LPU (Lovely Professional University)",
    "BITS Pilani - Goa Campus",
    "BITS Pilani - Hyderabad Campus",
    "University of Engineering and Management (UEM) Kolkata",
    "Mody University of Science and Technology",
    "Banasthali Vidyapith",
    "Hindu College, Delhi University",
    "St. Xavier's College, Mumbai",
    "St. Stephen's College, Delhi University",
    "Lady Shri Ram College, Delhi University",
    "Indian Institute of Information Technology (IIIT) Delhi",
    "Indian Institute of Information Technology (IIIT) Bangalore",
    "Indian Institute of Information Technology (IIIT) Hyderabad",
    "Indian Institute of Information Technology (IIIT) Allahabad",
    "Indian Institute of Information Technology (IIIT) Gwalior",
    "Indian Institute of Information Technology (IIIT) Pune",
    "Sastra University",
    "Indraprastha Institute of Information Technology (IIIT-Delhi)",
    "University of Rajasthan",
    "Maharashtra Institute of Technology (MIT Pune)",
    "VIT University - Bhopal",
    "University of Calcutta",
    "Bangalore University",
    "Birla Institute of Technology (BIT) Mesra",
    "Nirma University",
    "University of Madras",
    "Jawaharlal Nehru University (JNU)",
    "University of Delhi South Campus",
    "KIIT University",
    "Maharaja Agrasen Institute of Technology",
    "Ambedkar University, Delhi",
    "Mohanlal Sukhadia University, Udaipur",
    "National Institute of Technology (NIT) Jamshedpur",
    "Acharya Institute of Technology, Bangalore",
    "Indore Institute of Science and Technology",
    "Symbiosis Institute of Technology",
    "Institute of Management Technology (IMT) Ghaziabad",
    "International Institute of Information Technology (IIIT) Pune",
    "Indian School of Mines (ISM), Dhanbad",
    "Bangalore Institute of Technology",
    "Chandigarh University",
    "GITAM University",
    "University of Hyderabad",
    "Mahatma Gandhi University, Kottayam",
    "NIT Durgapur",
    "R.V. College of Engineering, Bangalore",
    "BMS College of Engineering",
    "University of Madras",
    "Indian Institute of Science (IISc), Bangalore",
    "National Institute of Design (NID)",
    "Maharaja Sayajirao University of Baroda",
    "St. Xavier’s College, Kolkata",
    "University of Science and Technology Meghalaya",
    "Indian Institute of Mass Communication (IIMC)",
    "Lalit Narayan Mishra Institute of Economic Development",
    "Goa University",
    "Jamia Millia Islamia - Faculty of Engineering and Technology",
    "Institute of Rural Management Anand (IRMA)",
    "University of Kashmir",
    "Aligarh Muslim University (AMU)",
    "Netaji Subhas University of Technology",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Maharashtra University of Health Sciences",
    "Sardar Vallabhbhai Patel Institute of Technology",
    "UPES University Dehradun",
    "PES University",
    "MIT World Peace University",
    "University of Petroleum and Energy Studies (UPES)",
    "Indira Gandhi Institute of Technology",
    "ICFAI Business School",
    "Vidyasagar University",
    "Shivaji University",
    "Rajiv Gandhi Institute of Technology (RGIT)",
    "Indian Statistical Institute",
    "Sathyabama Institute of Science and Technology",
    "Srinivas University",
    "St. Xavier's College, Ranchi",
    "Apeejay Stya University",
    "Nehru Group of Institutions (NGI)",
    "University of Pune",
    "Dr. APJ Abdul Kalam Technical University",
    "Rajasthan Technical University",
    "Shiv Nadar University",
    "Vellore Institute of Technology - Bhopal",
    "University of Allahabad",
    "University of Madras",
    "International Institute of Management Studies (IIMS)",
    "National Law University (NLU) Odisha",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Institute of Engineering and Technology Lucknow",
    "Mizoram University",
    "Chhattisgarh Swami Vivekanand Technical University",
    "Vignan’s Foundation for Science, Technology & Research",
    "Himachal Pradesh University",
    "University of Mumbai - Department of Technology",
    "University of Goa",
    "Kalinga Institute of Industrial Technology",
    "Sage University Indore",
    "Mysuru University",
    "Sardar Vallabhbhai National Institute of Technology (SVNIT)",
    "Institute of Technology Nirma University",
    "Madras University - Department of Engineering",
    "Shivaji University, Kolhapur",
    "Sastra University - School of Engineering",
    "Sri Sathya Sai University for Human Excellence",
    "University of Agricultural Sciences, Bangalore",
    "VIT University",
    "Utkal University",
    "Jadavpur University",
    "Bihar University",
    "Dr. B.R. Ambedkar University",
    "Bharath University",
    "North Eastern Hill University",
    "Maulana Azad National Institute of Technology",
    "Vivekananda College of Engineering and Technology",
    "St. Xavier’s College of Engineering",
    "SRM Institute of Science and Technology - Amaravati",
    "National Institute of Technology (NIT) Silchar",
    "Dr. Rajendra Prasad Central Agricultural University",
    "Chandigarh College of Engineering and Technology",
    "Dr. Bhim Rao Ambedkar University, Agra",
    "NIT Uttarakhand",
    "Sardar Patel University",
    "Bihar Engineering College",
    "Deenbandhu Chhotu Ram University of Science and Technology",
    "University of Kerala",
    "Dharamsinh Desai University",
    "Biju Patnaik University of Technology",
    "Indira Gandhi National Open University (IGNOU)",
    "Uttarakhand Technical University",
    "International Management Institute (IMI) Delhi",
    "Maharashtra State Board of Technical Education (MSBTE)",
    "Ramaiah Institute of Technology, Bangalore",
    "Birla Institute of Technology (BIT) Patna",
    "Shivaji University, Kolhapur",
    "MIT College of Engineering, Pune",
    "Adamas University",
    "Lakshmi Narain College of Technology",
    "University of Madras, Department of Technology",
    "Dr. G.R. Damodaran College of Science",
    "VIT Chennai",
    "Shree Sankaracharya University of Sanskrit",
    "Shiv Nadar University - Department of Engineering",
    "Indore Institute of Science & Technology (IIST)",
    "University of Jammu",
    "Galgotias College of Engineering and Technology",
    "Andhra University",
    "Ambedkar Institute of Technology",
    "Institute of Information Technology and Management",
    "Bharati Vidyapeeth University",
    "Tata Institute of Fundamental Research (TIFR)",
    "Doon University",
    "Manipal University Jaipur",
    "Pune University",
    "Shivaji College, Delhi University",
    "College of Engineering Pune (COEP)",
    "Alagappa University",
    "University of Mysore",
    "Jamia Millia Islamia - Faculty of Engineering",
    "Northeastern Hill University",
    "Osmania University",
    "University of Hyderabad - School of Engineering",
    "Rama Devi Women’s University",
    "Shiv Nadar University - Department of Science and Technology",
    "School of Planning and Architecture, Delhi",
    "IIT Gandhinagar",
    "IIT Indore",
    "Other",
  ],
  PG: [
    "IIT Bombay",
    "IIT Delhi",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT BHU",
    "NIT Trichy",
    "NIT Surathkal",
    "NIT Warangal",
    "NIT Calicut",
    "VIT Vellore",
    "BITS Pilani",
    "CU Chandigarh",
    "MIT Pune",
    "Amity University",
    "SRM Institute of Science and Technology",
    "Thapar University",
    "Punjab Engineering College",
    "Shiv Nadar University",
    "Manipal Institute of Technology",
    "University of Delhi",
    "Institute of Chemical Technology (ICT Mumbai)",
    "Jamia Millia Islamia",
    "Banaras Hindu University (BHU)",
    "Indian Institute of Engineering Science and Technology (IIEST)",
    "National Institute of Fashion Technology (NIFT)",
    "University of Pune",
    "University of Mumbai",
    "Indian Institute of Management (IIM) Indore",
    "Indian Institute of Management (IIM) Lucknow",
    "Indian Institute of Management (IIM) Ahmedabad",
    "Indian Institute of Management (IIM) Bangalore",
    "National Law University (NLU) Delhi",
    "National Law University (NLU) Jodhpur",
    "Jamia Hamdard University",
    "Dr. B.R. Ambedkar National Institute of Technology (NIT Jalandhar)",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "LPU (Lovely Professional University)",
    "BITS Pilani - Goa Campus",
    "BITS Pilani - Hyderabad Campus",
    "University of Engineering and Management (UEM) Kolkata",
    "Mody University of Science and Technology",
    "Banasthali Vidyapith",
    "Hindu College, Delhi University",
    "St. Xavier's College, Mumbai",
    "St. Stephen's College, Delhi University",
    "Lady Shri Ram College, Delhi University",
    "Indian Institute of Information Technology (IIIT) Delhi",
    "Indian Institute of Information Technology (IIIT) Bangalore",
    "Indian Institute of Information Technology (IIIT) Hyderabad",
    "Indian Institute of Information Technology (IIIT) Allahabad",
    "Indian Institute of Information Technology (IIIT) Gwalior",
    "Indian Institute of Information Technology (IIIT) Pune",
    "Sastra University",
    "Indraprastha Institute of Information Technology (IIIT-Delhi)",
    "University of Rajasthan",
    "Maharashtra Institute of Technology (MIT Pune)",
    "VIT University - Bhopal",
    "University of Calcutta",
    "Bangalore University",
    "Birla Institute of Technology (BIT) Mesra",
    "Nirma University",
    "University of Madras",
    "Jawaharlal Nehru University (JNU)",
    "University of Delhi South Campus",
    "KIIT University",
    "Maharaja Agrasen Institute of Technology",
    "Ambedkar University, Delhi",
    "Mohanlal Sukhadia University, Udaipur",
    "National Institute of Technology (NIT) Jamshedpur",
    "Acharya Institute of Technology, Bangalore",
    "Indore Institute of Science and Technology",
    "Symbiosis Institute of Technology",
    "Institute of Management Technology (IMT) Ghaziabad",
    "International Institute of Information Technology (IIIT) Pune",
    "Indian School of Mines (ISM), Dhanbad",
    "Bangalore Institute of Technology",
    "Chandigarh University",
    "GITAM University",
    "University of Hyderabad",
    "Mahatma Gandhi University, Kottayam",
    "NIT Durgapur",
    "R.V. College of Engineering, Bangalore",
    "BMS College of Engineering",
    "University of Madras",
    "Indian Institute of Science (IISc), Bangalore",
    "National Institute of Design (NID)",
    "Maharaja Sayajirao University of Baroda",
    "St. Xavier’s College, Kolkata",
    "University of Science and Technology Meghalaya",
    "Indian Institute of Mass Communication (IIMC)",
    "Lalit Narayan Mishra Institute of Economic Development",
    "Goa University",
    "Jamia Millia Islamia - Faculty of Engineering and Technology",
    "Institute of Rural Management Anand (IRMA)",
    "University of Kashmir",
    "Aligarh Muslim University (AMU)",
    "Netaji Subhas University of Technology",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Maharashtra University of Health Sciences",
    "Sardar Vallabhbhai Patel Institute of Technology",
    "UPES University Dehradun",
    "PES University",
    "MIT World Peace University",
    "University of Petroleum and Energy Studies (UPES)",
    "Indira Gandhi Institute of Technology",
    "ICFAI Business School",
    "Vidyasagar University",
    "Shivaji University",
    "Rajiv Gandhi Institute of Technology (RGIT)",
    "Indian Statistical Institute",
    "Sathyabama Institute of Science and Technology",
    "Srinivas University",
    "St. Xavier's College, Ranchi",
    "Apeejay Stya University",
    "Nehru Group of Institutions (NGI)",
    "University of Pune",
    "Dr. APJ Abdul Kalam Technical University",
    "Rajasthan Technical University",
    "Shiv Nadar University",
    "Vellore Institute of Technology - Bhopal",
    "University of Allahabad",
    "University of Madras",
    "International Institute of Management Studies (IIMS)",
    "National Law University (NLU) Odisha",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Institute of Engineering and Technology Lucknow",
    "Mizoram University",
    "Chhattisgarh Swami Vivekanand Technical University",
    "Vignan’s Foundation for Science, Technology & Research",
    "Himachal Pradesh University",
    "University of Mumbai - Department of Technology",
    "University of Goa",
    "Kalinga Institute of Industrial Technology",
    "Sage University Indore",
    "Mysuru University",
    "Sardar Vallabhbhai National Institute of Technology (SVNIT)",
    "Institute of Technology Nirma University",
    "Madras University - Department of Engineering",
    "Shivaji University, Kolhapur",
    "Sastra University - School of Engineering",
    "Sri Sathya Sai University for Human Excellence",
    "University of Agricultural Sciences, Bangalore",
    "VIT University",
    "Utkal University",
    "Jadavpur University",
    "Bihar University",
    "Dr. B.R. Ambedkar University",
    "Bharath University",
    "North Eastern Hill University",
    "Maulana Azad National Institute of Technology",
    "Vivekananda College of Engineering and Technology",
    "St. Xavier’s College of Engineering",
    "SRM Institute of Science and Technology - Amaravati",
    "National Institute of Technology (NIT) Silchar",
    "Dr. Rajendra Prasad Central Agricultural University",
    "Chandigarh College of Engineering and Technology",
    "Dr. Bhim Rao Ambedkar University, Agra",
    "NIT Uttarakhand",
    "Sardar Patel University",
    "Bihar Engineering College",
    "Deenbandhu Chhotu Ram University of Science and Technology",
    "University of Kerala",
    "Dharamsinh Desai University",
    "Biju Patnaik University of Technology",
    "Indira Gandhi National Open University (IGNOU)",
    "Uttarakhand Technical University",
    "International Management Institute (IMI) Delhi",
    "Maharashtra State Board of Technical Education (MSBTE)",
    "Ramaiah Institute of Technology, Bangalore",
    "Birla Institute of Technology (BIT) Patna",
    "Shivaji University, Kolhapur",
    "MIT College of Engineering, Pune",
    "Adamas University",
    "Lakshmi Narain College of Technology",
    "University of Madras, Department of Technology",
    "Dr. G.R. Damodaran College of Science",
    "VIT Chennai",
    "Shree Sankaracharya University of Sanskrit",
    "Shiv Nadar University - Department of Engineering",
    "Indore Institute of Science & Technology (IIST)",
    "University of Jammu",
    "Galgotias College of Engineering and Technology",
    "Andhra University",
    "Ambedkar Institute of Technology",
    "Institute of Information Technology and Management",
    "Bharati Vidyapeeth University",
    "Tata Institute of Fundamental Research (TIFR)",
    "Doon University",
    "Manipal University Jaipur",
    "Pune University",
    "Shivaji College, Delhi University",
    "College of Engineering Pune (COEP)",
    "Alagappa University",
    "University of Mysore",
    "Jamia Millia Islamia - Faculty of Engineering",
    "Northeastern Hill University",
    "Osmania University",
    "University of Hyderabad - School of Engineering",
    "Rama Devi Women’s University",
    "Shiv Nadar University - Department of Science and Technology",
    "School of Planning and Architecture, Delhi",
    "IIT Gandhinagar",
    "IIT Indore",
    "Other",
  ],
  PhD: [
    "IIT Bombay",
    "IIT Delhi",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT BHU",
    "NIT Trichy",
    "NIT Surathkal",
    "NIT Warangal",
    "NIT Calicut",
    "VIT Vellore",
    "BITS Pilani",
    "CU Chandigarh",
    "MIT Pune",
    "Amity University",
    "SRM Institute of Science and Technology",
    "Thapar University",
    "Punjab Engineering College",
    "Shiv Nadar University",
    "Manipal Institute of Technology",
    "University of Delhi",
    "Institute of Chemical Technology (ICT Mumbai)",
    "Jamia Millia Islamia",
    "Banaras Hindu University (BHU)",
    "Indian Institute of Engineering Science and Technology (IIEST)",
    "National Institute of Fashion Technology (NIFT)",
    "University of Pune",
    "University of Mumbai",
    "Indian Institute of Management (IIM) Indore",
    "Indian Institute of Management (IIM) Lucknow",
    "Indian Institute of Management (IIM) Ahmedabad",
    "Indian Institute of Management (IIM) Bangalore",
    "National Law University (NLU) Delhi",
    "National Law University (NLU) Jodhpur",
    "Jamia Hamdard University",
    "Dr. B.R. Ambedkar National Institute of Technology (NIT Jalandhar)",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "LPU (Lovely Professional University)",
    "BITS Pilani - Goa Campus",
    "BITS Pilani - Hyderabad Campus",
    "University of Engineering and Management (UEM) Kolkata",
    "Mody University of Science and Technology",
    "Banasthali Vidyapith",
    "Hindu College, Delhi University",
    "St. Xavier's College, Mumbai",
    "St. Stephen's College, Delhi University",
    "Lady Shri Ram College, Delhi University",
    "Indian Institute of Information Technology (IIIT) Delhi",
    "Indian Institute of Information Technology (IIIT) Bangalore",
    "Indian Institute of Information Technology (IIIT) Hyderabad",
    "Indian Institute of Information Technology (IIIT) Allahabad",
    "Indian Institute of Information Technology (IIIT) Gwalior",
    "Indian Institute of Information Technology (IIIT) Pune",
    "Sastra University",
    "Indraprastha Institute of Information Technology (IIIT-Delhi)",
    "University of Rajasthan",
    "Maharashtra Institute of Technology (MIT Pune)",
    "VIT University - Bhopal",
    "University of Calcutta",
    "Bangalore University",
    "Birla Institute of Technology (BIT) Mesra",
    "Nirma University",
    "University of Madras",
    "Jawaharlal Nehru University (JNU)",
    "University of Delhi South Campus",
    "KIIT University",
    "Maharaja Agrasen Institute of Technology",
    "Ambedkar University, Delhi",
    "Mohanlal Sukhadia University, Udaipur",
    "National Institute of Technology (NIT) Jamshedpur",
    "Acharya Institute of Technology, Bangalore",
    "Indore Institute of Science and Technology",
    "Symbiosis Institute of Technology",
    "Institute of Management Technology (IMT) Ghaziabad",
    "International Institute of Information Technology (IIIT) Pune",
    "Indian School of Mines (ISM), Dhanbad",
    "Bangalore Institute of Technology",
    "Chandigarh University",
    "GITAM University",
    "University of Hyderabad",
    "Mahatma Gandhi University, Kottayam",
    "NIT Durgapur",
    "R.V. College of Engineering, Bangalore",
    "BMS College of Engineering",
    "University of Madras",
    "Indian Institute of Science (IISc), Bangalore",
    "National Institute of Design (NID)",
    "Maharaja Sayajirao University of Baroda",
    "St. Xavier’s College, Kolkata",
    "University of Science and Technology Meghalaya",
    "Indian Institute of Mass Communication (IIMC)",
    "Lalit Narayan Mishra Institute of Economic Development",
    "Goa University",
    "Jamia Millia Islamia - Faculty of Engineering and Technology",
    "Institute of Rural Management Anand (IRMA)",
    "University of Kashmir",
    "Aligarh Muslim University (AMU)",
    "Netaji Subhas University of Technology",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Maharashtra University of Health Sciences",
    "Sardar Vallabhbhai Patel Institute of Technology",
    "UPES University Dehradun",
    "PES University",
    "MIT World Peace University",
    "University of Petroleum and Energy Studies (UPES)",
    "Indira Gandhi Institute of Technology",
    "ICFAI Business School",
    "Vidyasagar University",
    "Shivaji University",
    "Rajiv Gandhi Institute of Technology (RGIT)",
    "Indian Statistical Institute",
    "Sathyabama Institute of Science and Technology",
    "Srinivas University",
    "St. Xavier's College, Ranchi",
    "Apeejay Stya University",
    "Nehru Group of Institutions (NGI)",
    "University of Pune",
    "Dr. APJ Abdul Kalam Technical University",
    "Rajasthan Technical University",
    "Shiv Nadar University",
    "Vellore Institute of Technology - Bhopal",
    "University of Allahabad",
    "University of Madras",
    "International Institute of Management Studies (IIMS)",
    "National Law University (NLU) Odisha",
    "Rajiv Gandhi University of Knowledge Technologies",
    "Institute of Engineering and Technology Lucknow",
    "Mizoram University",
    "Chhattisgarh Swami Vivekanand Technical University",
    "Vignan’s Foundation for Science, Technology & Research",
    "Himachal Pradesh University",
    "University of Mumbai - Department of Technology",
    "University of Goa",
    "Kalinga Institute of Industrial Technology",
    "Sage University Indore",
    "Mysuru University",
    "Sardar Vallabhbhai National Institute of Technology (SVNIT)",
    "Institute of Technology Nirma University",
    "Madras University - Department of Engineering",
    "Shivaji University, Kolhapur",
    "Sastra University - School of Engineering",
    "Sri Sathya Sai University for Human Excellence",
    "University of Agricultural Sciences, Bangalore",
    "VIT University",
    "Utkal University",
    "Jadavpur University",
    "Bihar University",
    "Dr. B.R. Ambedkar University",
    "Bharath University",
    "North Eastern Hill University",
    "Maulana Azad National Institute of Technology",
    "Vivekananda College of Engineering and Technology",
    "St. Xavier’s College of Engineering",
    "SRM Institute of Science and Technology - Amaravati",
    "National Institute of Technology (NIT) Silchar",
    "Dr. Rajendra Prasad Central Agricultural University",
    "Chandigarh College of Engineering and Technology",
    "Dr. Bhim Rao Ambedkar University, Agra",
    "NIT Uttarakhand",
    "Sardar Patel University",
    "Bihar Engineering College",
    "Deenbandhu Chhotu Ram University of Science and Technology",
    "University of Kerala",
    "Dharamsinh Desai University",
    "Biju Patnaik University of Technology",
    "Indira Gandhi National Open University (IGNOU)",
    "Uttarakhand Technical University",
    "International Management Institute (IMI) Delhi",
    "Maharashtra State Board of Technical Education (MSBTE)",
    "Ramaiah Institute of Technology, Bangalore",
    "Birla Institute of Technology (BIT) Patna",
    "Shivaji University, Kolhapur",
    "MIT College of Engineering, Pune",
    "Adamas University",
    "Lakshmi Narain College of Technology",
    "University of Madras, Department of Technology",
    "Dr. G.R. Damodaran College of Science",
    "VIT Chennai",
    "Shree Sankaracharya University of Sanskrit",
    "Shiv Nadar University - Department of Engineering",
    "Indore Institute of Science & Technology (IIST)",
    "University of Jammu",
    "Galgotias College of Engineering and Technology",
    "Andhra University",
    "Ambedkar Institute of Technology",
    "Institute of Information Technology and Management",
    "Bharati Vidyapeeth University",
    "Tata Institute of Fundamental Research (TIFR)",
    "Doon University",
    "Manipal University Jaipur",
    "Pune University",
    "Shivaji College, Delhi University",
    "College of Engineering Pune (COEP)",
    "Alagappa University",
    "University of Mysore",
    "Jamia Millia Islamia - Faculty of Engineering",
    "Northeastern Hill University",
    "Osmania University",
    "University of Hyderabad - School of Engineering",
    "Rama Devi Women’s University",
    "Shiv Nadar University - Department of Science and Technology",
    "School of Planning and Architecture, Delhi",
    "IIT Gandhinagar",
    "IIT Indore",
  ],
};


export const degrees = {
  UG: [
    "BCA",
    "BSc",
    "BTech",
    "BA",
    "BCom",
    "BBA",
    "BHM",
    "BDS",
    "LLB",
    "BFA",
    "BAMS",
    "BPT",
    "BPharm",
    "BVSc",
    "BBA+LLB",
    "BTech+MTech",
  ],
  PG: [
    "MTech",
    "MCA",
    "MCS",
    "MBA",
    "MA",
    "MSc",
    "MCom",
    "MSW",
    "MPhil",
    "LLM",
    "MDS",
    "MPT",
    "MPharm",
    "MVSc",
    "MD",
    "MFA",
    "MCA+PhD",
  ],
};

export const specializations = {
  UG: {
    BCA: ["IT", "CS", "Maths", "Network Administration", "Database Management"],
    BSc: ["IT", "Physics", "Chemistry", "Maths", "Biology", "Biotechnology", "Environmental Science"],
    BTech: ["IT", "CS", "Mechanical", "ECE", "Civil", "Electrical", "Chemical", "Aerospace", "Automobile", "Electronics", "Industrial", "Mining"],
    BCom: ["General", "Accounting", "Finance", "Banking", "Taxation"],
    BA: ["English", "History", "Psychology", "Sociology", "Political Science", "Philosophy", "Economics"],
    BBA: ["General Management", "Human Resources", "Marketing", "Finance", "International Business"],
    BHM: ["Hotel Management", "Catering", "Event Management"],
    BDS: ["Dentistry"],
    LLB: ["General Law", "Corporate Law", "Criminal Law", "Family Law", "Intellectual Property Law"],
    BFA: ["Fine Arts", "Painting", "Sculpture", "Graphics"],
    BAMS: ["Ayurveda"],
    BPT: ["Physiotherapy"],
    BPharm: ["Pharmacy"],
    BVSc: ["Veterinary Science"],
    BBALLB: ["Business Law", "Corporate Law", "Civil Law"],
    "BTech+MTech": ["Computer Science", "Mechanical Engineering", "Electrical Engineering"],
  },
  PG: {
    MTech: ["IT", "CS", "Mechanical", "ECE", "Civil", "Electrical", "Aerospace", "Data Science", "Artificial Intelligence", "Robotics", "Structural Engineering", "VLSI Design"],
    MCA: ["IT", "CS", "Software Engineering", "Data Analytics", "Cloud Computing", "Network Security"],
    MCS: ["CS", "Data Science", "AI", "Big Data", "Cyber Security", "Machine Learning", "Data Engineering"],
    MBA: ["General Management", "Marketing", "Finance", "Human Resources", "Operations", "International Business", "Entrepreneurship", "Strategy", "Supply Chain Management"],
    MA: ["English", "Political Science", "History", "Economics", "Philosophy", "Sociology", "Psychology", "Journalism", "Public Administration"],
    MSc: ["Physics", "Chemistry", "Mathematics", "Biology", "Botany", "Zoology", "Microbiology", "Biotechnology", "Computer Science", "Environmental Science", "Statistics"],
    MCom: ["Commerce", "Finance", "Accounting", "Taxation"],
    MSW: ["Social Work", "Community Development", "Child Welfare", "Health Care"],
    MPhil: ["English", "History", "Sociology", "Psychology", "Political Science"],
    LLM: ["Constitutional Law", "Corporate Law", "Criminal Law", "Intellectual Property Rights", "Environmental Law"],
    MDS: ["Orthodontics", "Periodontology", "Prosthodontics", "Oral Surgery", "Conservative Dentistry"],
    MPT: ["Orthopaedic Physiotherapy", "Neurological Physiotherapy", "Sports Physiotherapy", "Cardiopulmonary Physiotherapy"],
    MPharm: ["Pharmaceutical Chemistry", "Pharmacology", "Pharmacy Practice", "Pharmacognosy", "Industrial Pharmacy"],
    MVSc: ["Animal Breeding", "Veterinary Pathology", "Veterinary Surgery", "Animal Nutrition", "Veterinary Medicine"],
    MD: ["General Medicine", "Pediatrics", "Orthopedics", "Surgery", "Obstetrics and Gynecology", "Psychiatry", "Dermatology"],
    MFA: ["Fine Arts", "Painting", "Sculpture", "Photography"],
    "MCA+PhD": ["Software Engineering", "Cloud Computing", "Data Science", "Artificial Intelligence", "Machine Learning"],
  },
};


export const skillSuggestions = [
  "JavaScript",
  "HTML",
  "CSS",
  "React.js",
  "Node.js",
  "Java",
  "Python",
  "SQL",
  "TypeScript",
  "MongoDB",
  "Git",
  "Docker",
  "GraphQL",
  "AWS",
  "Azure",
  "DevOps",
  "Android",
  "Swift",
  "Ruby",
  "C#",
  "Go",
  "PHP",
  "C++",
  "Kotlin",
  "Scala",
  "Rust",
  "Flutter",
  "Vue.js",
  "Angular",
  "Express.js",
  "Laravel",
  "Team Lead", // Example of a soft skill
  "Communication", // Soft Skills
  "Problem Solving",
  "Time Management",
  "Leadership",
  "Teamwork",
  "Adaptability",
  "Creativity",
  "Collaboration",
  "Critical Thinking",
  "Decision Making",
  "Conflict Resolution",
  "Public Speaking",
  "Emotional Intelligence",
  "Work Ethic",
];


export const domain = [
  "Finance",
  "Energy",
  "Health",
  "IT",
  "Education",
  "Retail",
  "Manufacturing",
  "Automotive",
  "Real Estate",
  "Telecommunications",
  "E-commerce",
  "Agriculture",
  "Logistics",
  "Entertainment",
  "Media",
  "Gaming",
  "Hospitality",
  "Government",
  "Pharmaceuticals",
  "Construction",
  "Aerospace",
  "Transportation",
  "Insurance",
  "Legal",
  "Cybersecurity",
  "Blockchain",
  "Artificial Intelligence",
  "Data Science",
  "Sustainability",
  "Nonprofit",
  "Research",
  "Consumer Goods",
  "Biotechnology",
  "Travel",
  "Marketing",
  "Consulting",
  "Supply Chain",
  "Food and Beverage",
  "Other",
];