export const jobTitleSuggestions = [
  "Software Development Engineer (SDE) 1",
  "Software Development Engineer (SDE) 2",
  "Software Development Engineer (SDE) 3",
  "Java Developer",
  "Python Developer",
  "PHP Developer",
  "React.js Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Financial Software Developer",
  "Quantitative Analyst",
  "Data Engineer (Finance Sector)",
  "Blockchain Developer",
  "Risk Management Analyst",
  "FinTech Developer",
  "Algorithmic Trader",
  "Health IT Specialist",
  "Bioinformatics Developer",
  "Medical Data Analyst",
  "Software Engineer (Healthcare Applications)",
  "AI Specialist (Healthcare Sector)",
  "Health Information Systems Engineer",
  "EHR/EMR Systems Developer",
  "Renewable Energy Systems Developer",
  "Energy Data Analyst",
  "Smart Grid Software Engineer",
  "IoT Developer (Energy Sector)",
  "Energy Efficiency Analyst",
  "Software Engineer (Energy Management Systems)",
  "AI Specialist (Energy Sector)",
];
