// Location data (countries, states, and cities)
export const locationData = {
  India: {
    Andhra_Pradesh: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Kakinada",
      "Tirupati",
      "Anantapur",
      "Kadapa",
      "Eluru",
      "Chittoor",
      "Ongole",
      "Vizianagaram",
      "Machilipatnam",
      "Adoni",
      "Tenali",
      "Proddatur",
      "Hindupur",
      "Bhimavaram",
      "Madanapalle",
      "Guntakal",
      "Srikakulam",
      "Nandyal",
      "Chilakaluripet",
      "Anakapalle",
      "Tadipatri",
      "Tadepalligudem",
      "Amalapuram",
      "Palasa",
      "Kovvur",
      "Rayachoti",
      "Narasaraopet",
      "Dharmavaram",
      "Nagari",
      "Vinukonda",
      "Bapatla",
      "Pithapuram",
      "Narsapur",
      "Tuni",
      "Sattenapalle",
      "Markapur",
      "Gudivada",
      "Nuzvid",
      "Samalkot",
      "Punganur",
      "Kandukur",
      "Palamaner",
      "Kavali",
      "Yemmiganur",
      "Sullurpet",
      "Jaggayyapeta",
      "Macherla",
      "Salur",
      "Chirala",
      "Mandapeta",
      "Bobbili",
      "Tiruvuru",
      "Rajam",
      "Naidupet",
    ],
    Arunachal_Pradesh: [
      "Itanagar",
      "Tawang",
      "Ziro",
      "Pasighat",
      "Bomdila",
      "Tezu",
      "Aalo",
      "Roing",
      "Seppa",
      "Khonsa",
      "Daporijo",
      "Yingkiong",
      "Changlang",
      "Anini",
      "Namsai",
      "Koloriang",
      "Jairampur",
      "Pangin",
      "Miao",
      "Naharlagun",
    ],
    Assam: [
      "Guwahati",
      "Dibrugarh",
      "Silchar",
      "Jorhat",
      "Tinsukia",
      "Nagaon",
      "Tezpur",
      "Bongaigaon",
      "Bihpuria",
      "Barpeta",
      "Golaghat",
      "Hailakandi",
      "Nalbari",
      "Sivasagar",
      "Lakhimpur",
      "Karimganj",
      "Darrang",
      "Cachar",
      "Morigaon",
      "Sonitpur",
      "Dima Hasao",
      "Kamrup",
      "Kamrup Metropolitan",
      "Baksa",
      "Chirang",
      "Udalguri",
      "Dhubri",
      "Kokrajhar",
      "Bongaigaon",
      "Hojai",
      "Dibrugarh",
      "Bongaigaon",
      "Sontipur",
      "Hailakandi",
      "Biswanath",
    ],
    Bihar: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Munger",
      "Buxar",
      "Nalanda",
      "Sasaram",
      "Chapra",
      "Arrah",
      "Begusarai",
      "Bhagalpur",
      "Samastipur",
      "Hajipur",
      "Bettiah",
      "Motihari",
      "Khagaria",
      "Sitamarhi",
      "Vaishali",
      "Siwan",
      "Kishanganj",
      "Lakhisarai",
      "Jahanabad",
      "Nawada",
      "Kaimur",
      "Banka",
      "West Champaran",
      "East Champaran",
      "Sheohar",
      "Madhubani",
      "Shahabad",
      "Gopalganj",
      "Jamui",
      "Supaul",
      "Madhepura",
      "Samastipur",
      "Buxar",
    ],
    Chhattisgarh: [
      "Raipur",
      "Bilaspur",
      "Durg",
      "Korba",
      "Raigarh",
      "Jagdalpur",
      "Dhamtari",
      "Rajnandgaon",
      "Korea",
      "Janjgir-Champa",
      "Mahasamund",
      "Surguja",
      "Balod",
      "Bemetara",
      "Kondagaon",
      "Mungeli",
      "Balrampur",
      "Narayanpur",
      "Surajpur",
      "Bijapur",
      "Gariaband",
      "Kanker",
      "Kabirdham",
      "Bijapur",
      "Chirmiri",
      "Ambikapur",
      "Dongargarh",
      "Sakti",
      "Bilaspur",
      "Raigarh",
      "Durg",
    ],
    Goa: [
      "Panaji",
      "Margao",
      "Mapusa",
      "Vasco da Gama",
      "Ponda",
      "Porvorim",
      "Curchorem",
      "Bicholim",
      "Quepem",
      "Sanquelim",
      "Dona Paula",
      "Anjuna",
      "Calangute",
      "Candolim",
      "Arambol",
      "Baga",
      "Colva",
      "Varca",
      "Palolem",
      "Agonda",
      "Majorda",
      "Betul",
      "Sangolda",
      "Benaulim",
      "Cortalim",
      "Chandor",
      "Navelim",
      "Raia",
    ],
    Gujarat: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Vapi",
      "Junagadh",
      "Anand",
      "Gandhinagar",
      "Nadiad",
      "Navsari",
      "Mehsana",
      "Veraval",
      "Morbi",
      "Amreli",
      "Bharuch",
      "Patan",
      "Godhra",
      "Porbandar",
      "Kheda",
      "Dholka",
      "Visnagar",
      "Palitana",
      "Daman",
      "Dwarka",
      "Mahesana",
      "Valsad",
      "Kankaria",
      "Navagam",
      "Unjha",
      "Bhiloda",
      "Bardoli",
      "Wadhwan",
      "Sihor",
      "Halol",
      "Chhota Udaipur",
      "Bhuj",
      "Radhanpur",
      "Modasa",
    ],
    Haryana: [
      "Gurgaon",
      "Faridabad",
      "Ambala",
      "Karnal",
      "Hisar",
      "Panipat",
      "Rohtak",
      "Sonipat",
      "Yamunanagar",
      "Kalka",
      "Bhiwani",
      "Palwal",
      "Mahendragarh",
      "Fatehabad",
      "Sirsa",
      "Rewari",
      "Narnaul",
      "Jhajjar",
      "Charkhi Dadri",
      "Kurukshetra",
      "Jind",
      "Gohana",
      "Hodal",
      "Assandh",
      "Beri",
      "Dabwali",
      "Nuh",
      "Tosham",
      "Bawal",
      "Loharu",
    ],
    Himachal_Pradesh: [
      "Shimla",
      "Manali",
      "Kullu",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Kangra",
      "Bilaspur",
      "Hamirpur",
      "Nahan",
      "Palampur",
      "Chamba",
      "Kasauli",
      "Kangra",
      "Una",
      "Chandpur",
      "Rohru",
      "Arki",
      "Nalagarh",
      "Baijnath",
      "Sundernagar",
      "Chintpurni",
      "Narkanda",
      "Jubbal",
      "Sirmaur",
      "Chhota Bhangal",
      "Baddi",
      "Fatehpur",
    ],
    Jharkhand: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Hazaribagh",
      "Deoghar",
      "Giridih",
      "Dumka",
      "Chaibasa",
      "Jhumri Tilaiya",
      "Ramgarh",
      "Koderma",
      "Palamu",
      "Khunti",
      "Pakur",
      "Simdega",
      "Godda",
      "Sahebganj",
      "Latehar",
      "Chatra",
      "West Singhbhum",
      "East Singhbhum",
      "Lohardaga",
      "Saraikela",
      "Madhupur",
      "Koderma",
      "Barhi",
      "Bermo",
      "Kolkata (part of Jharkhand)",
    ],
    Karnataka: [
      "Bangalore",
      "Mysore",
      "Mangalore",
      "Hubli",
      "Dharwad",
      "Belgaum",
      "Bijapur",
      "Shivamogga",
      "Ballari",
      "Chitradurga",
      "Tumkur",
      "Mandya",
      "Udupi",
      "Raichur",
      "Chikmagalur",
      "Hassan",
      "Bagalkot",
      "Kolar",
      "Ramanagaram",
      "Kodagu",
      "Dakshina Kannada",
      "Chikkaballapur",
      "Gulbarga",
      "Bidar",
      "Haveri",
      "Yadgir",
      "Koppal",
      "Karwar",
      "Srirangapatna",
      "Puttur",
      "Anekal",
      "Vijayapura",
      "Sakleshpur",
      "Hunsur",
      "Gadag",
      "Raichur",
      "Karwar",
      "Challakere",
      "Alur",
    ],
    Kerala: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Malappuram",
      "Kannur",
      "Alappuzha",
      "Palakkad",
      "Kottayam",
      "Pathanamthitta",
      "Wayanad",
      "Idukki",
      "Ernakulam",
      "Kasaragod",
      "Nelliyampathy",
      "Munnar",
      "Varkala",
      "Sabarimala",
      "Changanassery",
      "Punalur",
      "Ottapalam",
      "Cherthala",
      "Kayani",
      "Angamaly",
      "Manjeri",
      "Nilambur",
      "Vadakara",
      "Paravur",
      "Nedumangadu",
      "Perumbavoor",
      "Palai",
      "Kottarakkara",
    ],
    Madhya_Pradesh: [
      "Bhopal",
      "Indore",
      "Gwalior",
      "Jabalpur",
      "Ujjain",
      "Sagar",
      "Ratlam",
      "Satna",
      "Rewa",
      "Khandwa",
      "Chhindwara",
      "Shivpuri",
      "Dewas",
      "Bhind",
      "Mandsaur",
      "Sehore",
      "Dhar",
      "Neemuch",
      "Burhanpur",
      "Khargone",
      "Vidisha",
      "Hoshangabad",
      "Tikamgarh",
      "Pachmarhi",
      "Rajgarh",
      "Shahdol",
      "Ujjain",
      "Damoh",
      "Narsinghpur",
      "Sidhi",
      "Seoni",
      "Balaghat",
      "Alirajpur",
      "Khandwa",
      "Mandla",
      "Mauganj",
      "Panna",
      "Shivpuri",
      "Barwani",
      "Betul",
      "Mandla",
      "Ashoknagar",
    ],
    Maharashtra: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Thane",
      "Kolhapur",
      "Satara",
      "Amravati",
      "Jalgaon",
      "Ratnagiri",
      "Chandrapur",
      "Latur",
      "Akola",
      "Nanded",
      "Bhivandi",
      "Ulhasnagar",
      "Kalyan",
      "Dombivli",
      "Parbhani",
      "Dhule",
      "Sangli",
      "Yavatmal",
      "Bhusawal",
      "Chiplun",
      "Vasai-Virar",
      "Raigad",
      "Shirdi",
      "Aurangabad",
      "Bhandara",
      "Wardha",
      "Nagpur",
      "Miraj",
      "Vengurla",
      "Sindhudurg",
      "Khamgaon",
      "Akola",
      "Jalna",
      "Gadchiroli",
      "Bhandara",
      "Worli",
      "Matheran",
    ],
    Manipur: [
      "Imphal",
      "Churachandpur",
      "Bishnupur",
      "Thoubal",
      "Kangpokpi",
      "Senapati",
      "Ukhrul",
      "Tengnoupal",
      "Chandel",
      "Tamenglong",
      "Noney",
      "Jiribam",
      "Kakching",
      "Moirang",
      "Mayang Imphal",
      "Lamlai",
      "Kumbi",
      "Yairipok",
      "Wangoi",
      "Tungjoy",
      "Mongsangei",
    ],
    Meghalaya: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongstoin",
      "Williamnagar",
      "Baghmara",
      "Mawkyrwat",
      "Nongpoh",
      "Pynursla",
      "Laban",
      "Mawlai",
      "Cherrapunji",
      "Polo",
      "Rangthong",
      "Khasi Hills",
      "Garo Hills",
      "Ri-Bhoi",
    ],
    Mizoram: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Kolasib",
      "Serchhip",
      "Mamit",
      "Lawngtlai",
      "Hnahthial",
      "Saitual",
      "Khawzawl",
      "Thingdawl",
      "Lungdar",
      "Tlabung",
      "Khawhai",
      "Bungkawn",
      "Zohnuai",
      "Reiek",
      "Darlawn",
    ],
    Nagaland: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Wokha",
      "Zunheboto",
      "Peren",
      "Tuensang",
      "Mon",
      "Longleng",
      "Kiphire",
      "Phek",
      "Chümoukedima",
      "Medziphema",
      "Tseminyu",
      "Jalukie",
    ],
    Odisha: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Balasore",
      "Bargarh",
      "Angul",
      "Koraput",
      "Dhenkanal",
      "Jeypore",
      "Puri",
      "Jharsuguda",
      "Bhadrak",
      "Kendrapara",
      "Nayagarh",
      "Keonjhar",
      "Kalahandi",
      "Malkangiri",
      "Mayurbhanj",
      "Rayagada",
      "Ganjam",
      "Boudh",
      "Nuapada",
      "Sundargarh",
      "Jagatsinghpur",
      "Puri",
      "Cuttack",
      "Rairangpur",
      "Phulbani",
    ],
    Punjab: [
      "Chandigarh",
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Moga",
      "Hoshiarpur",
      "Pathankot",
      "Kapurthala",
      "Firozpur",
      "Fatehgarh Sahib",
      "Rupnagar",
      "Gurdaspur",
      "Barnala",
      "Sri Muktsar Sahib",
      "Sangrur",
      "Faridkot",
      "Tarn Taran",
      "Zira",
      "Dinanagar",
      "Khanna",
      "Samrala",
      "Phagwara",
      "Bassi Pathana",
      "Ajnala",
      "Mansa",
    ],
    Rajasthan: [
      "Jaipur",
      "Udaipur",
      "Jodhpur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Sikar",
      "Pali",
      "Churu",
      "Bhilwara",
      "Jaisalmer",
      "Tonk",
      "Sawai Madhopur",
      "Barmer",
      "Nagaur",
      "Bundi",
      "Dungarpur",
      "Ratangarh",
      "Chittorgarh",
      "Karauli",
      "Jhunjhunu",
      "Rajsamand",
      "Jhalawar",
      "Sirohi",
      "Hanumangarh",
      "Banswara",
      "Pratapgarh",
      "Baran",
      "Dholpur",
      "Dausa",
      "Merta",
    ],
    Sikkim: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Pakyong",
      "Rangpo",
      "Jorethang",
      "Singtam",
      "Rongli",
      "Temi",
      "Soreng",
      "Martam",
      "Tadong",
      "Lower Pelling",
      "Upper Pelling",
      "Melli",
      "Lachung",
      "Yuksom",
    ],
    Tamil_Nadu: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Tiruppur",
      "Vellore",
      "Dindigul",
      "Thanjavur",
      "Nagercoil",
      "Kanchipuram",
      "Karur",
      "Sivakasi",
      "Cuddalore",
      "Virudhunagar",
      "Chidambaram",
      "Ramanathapuram",
      "Kumarapalayam",
      "Pudukkottai",
      "Perambalur",
      "Dharmapuri",
      "Nagapattinam",
      "Thoothukudi",
      "Kancheepuram",
      "Rajapalayam",
      "Ariyalur",
      "Villupuram",
      "Ambur",
      "Tiruvannamalai",
      "Polur",
      "Kovilpatti",
      "Sankarankovil",
      "Vikramasingapuram",
      "Rishivandiyam",
    ],
    Telangana: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Khammam",
      "Karimnagar",
      "Nalgonda",
      "Mahabubnagar",
      "Ramagundam",
      "Suryapet",
      "Miryalaguda",
      "Jagitial",
      "Kothagudem",
      "Siddipet",
      "Adilabad",
      "Peddapalli",
      "Medak",
      "Jagtial",
      "Bhongir",
      "Jubilee Hills",
      "Boduppal",
      "Hayathnagar",
      "Secunderabad",
      "Malkajgiri",
      "LB Nagar",
      "Ameerpet",
      "Kukatpally",
      "Malkajgiri",
      "Narsingi",
    ],
    Tripura: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Ambassa",
      "Kailashahar",
      "Belonia",
      "Sabroom",
      "Sonamura",
      "Khowai",
      "Teliamura",
      "Melaghar",
      "Manu",
      "Kamalanagar",
      "Amarpur",
      "Charilam",
      "Mohanpur",
      "Jirania",
    ],
    Uttar_Pradesh: [
      "Agra",
      "Aligarh",
      "Allahabad (Prayagraj)",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad (Ayodhya)",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar (Noida)",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Raebareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shrawasti",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
    Uttarakhand: [
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Rishikesh",
      "Roorkee",
      "Almora",
      "Haldwani",
      "Rudrapur",
      "Kotdwar",
      "Pauri",
      "Haridwar",
      "Tehri",
      "Kashipur",
      "Vikasnagar",
      "Lansdowne",
      "Kedarnath",
      "Badrinath",
      "Pithoragarh",
      "Champawat",
      "Bijnor",
      "Srinagar",
    ],
    West_Bengal: [
      "Kolkata",
      "Darjeeling",
      "Howrah",
      "Siliguri",
      "Durgapur",
      "Asansol",
      "Murshidabad",
      "Kalyani",
      "Haldia",
      "Bolpur",
      "Medinipur",
      "Jalpaiguri",
      "Bankura",
      "Chandannagar",
      "Purulia",
      "Berhampore",
      "Cooch Behar",
      "Malda",
      "Bardhaman",
      "Kolar",
      "Raghunathganj",
      "Sainthia",
      "Bongaon",
      "Raiganj",
      "Contai",
      "Bishnupur",
      "Kurseong",
      "Alambazar",
      "Suri",
      "Kolkata Suburban",
    ],
  },
  USA: {
    California: ["Los Angeles", "San Francisco", "San Diego"],
    Texas: ["Houston", "Dallas", "Austin"],
    Florida: ["Miami", "Orlando", "Tampa"],
  },
  Australia: {
    Victoria: ["Melbourne", "Geelong", "Ballarat"],
    Queensland: ["Brisbane", "Gold Coast", "Cairns"],
    New_South_Wales: ["Sydney", "Newcastle", "Wollongong"],
  },
  Canada: {
    Ontario: ["Toronto", "Ottawa", "Hamilton"],
    Quebec: ["Montreal", "Quebec City", "Laval"],
    Alberta: ["Calgary", "Edmonton", "Red Deer"],
  },
  Germany: {
    Bavaria: ["Munich", "Nuremberg", "Augsburg"],
    Berlin: ["Berlin City"],
    Hesse: ["Frankfurt", "Wiesbaden", "Darmstadt"],
  },
  United_Kingdom: {
    England: ["London", "Manchester", "Liverpool"],
    Scotland: ["Edinburgh", "Glasgow", "Aberdeen"],
    Wales: ["Cardiff", "Swansea", "Newport"],
  },
  France: {
    Ile_de_France: ["Paris", "Versailles"],
    Provence: ["Marseille", "Nice", "Avignon"],
    Normandy: ["Rouen", "Caen", "Le Havre"],
  },
  Japan: {
    Tokyo: ["Tokyo City", "Shibuya", "Shinjuku"],
    Osaka: ["Osaka City", "Sakai", "Higashiosaka"],
    Hokkaido: ["Sapporo", "Hakodate", "Asahikawa"],
  },
  China: {
    Beijing: ["Beijing City", "Haidian", "Chaoyang"],
    Shanghai: ["Shanghai City", "Pudong", "Huangpu"],
    Guangdong: ["Guangzhou", "Shenzhen", "Foshan"],
  },
  Brazil: {
    São_Paulo: ["São Paulo City", "Campinas", "Santos"],
    Rio_de_Janeiro: ["Rio City", "Niterói", "Nova Iguaçu"],
    Bahia: ["Salvador", "Feira de Santana", "Vitória da Conquista"],
  },
  




  
};


export const countryList = [
  { code: "AF", country: "Afghanistan", phoneCode: "+93" },
  { code: "AL", country: "Albania", phoneCode: "+355" },
  { code: "DZ", country: "Algeria", phoneCode: "+213" },
  { code: "AS", country: "American Samoa", phoneCode: "+1-684" },
  { code: "AD", country: "Andorra", phoneCode: "+376" },
  { code: "AO", country: "Angola", phoneCode: "+244" },
  { code: "AI", country: "Anguilla", phoneCode: "+1-264" },
  { code: "AQ", country: "Antarctica", phoneCode: "+672" },
  { code: "AG", country: "Antigua and Barbuda", phoneCode: "+1-268" },
  { code: "AR", country: "Argentina", phoneCode: "+54" },
  { code: "AM", country: "Armenia", phoneCode: "+374" },
  { code: "AW", country: "Aruba", phoneCode: "+297" },
  { code: "AU", country: "Australia", phoneCode: "+61" },
  { code: "AT", country: "Austria", phoneCode: "+43" },
  { code: "AZ", country: "Azerbaijan", phoneCode: "+994" },
  { code: "BS", country: "Bahamas", phoneCode: "+1-242" },
  { code: "BH", country: "Bahrain", phoneCode: "+973" },
  { code: "BD", country: "Bangladesh", phoneCode: "+880" },
  { code: "BB", country: "Barbados", phoneCode: "+1-246" },
  { code: "BY", country: "Belarus", phoneCode: "+375" },
  { code: "BE", country: "Belgium", phoneCode: "+32" },
  { code: "BZ", country: "Belize", phoneCode: "+501" },
  { code: "BJ", country: "Benin", phoneCode: "+229" },
  { code: "BM", country: "Bermuda", phoneCode: "+1-441" },
  { code: "BT", country: "Bhutan", phoneCode: "+975" },
  { code: "BO", country: "Bolivia", phoneCode: "+591" },
  { code: "BA", country: "Bosnia and Herzegovina", phoneCode: "+387" },
  { code: "BW", country: "Botswana", phoneCode: "+267" },
  { code: "BR", country: "Brazil", phoneCode: "+55" },
  { code: "IO", country: "British Indian Ocean Territory", phoneCode: "+246" },
  { code: "BN", country: "Brunei", phoneCode: "+673" },
  { code: "BG", country: "Bulgaria", phoneCode: "+359" },
  { code: "BF", country: "Burkina Faso", phoneCode: "+226" },
  { code: "BI", country: "Burundi", phoneCode: "+257" },
  { code: "KH", country: "Cambodia", phoneCode: "+855" },
  { code: "CM", country: "Cameroon", phoneCode: "+237" },
  { code: "CA", country: "Canada", phoneCode: "+1" },
  { code: "CV", country: "Cape Verde", phoneCode: "+238" },
  { code: "KY", country: "Cayman Islands", phoneCode: "+1-345" },
  { code: "CF", country: "Central African Republic", phoneCode: "+236" },
  { code: "TD", country: "Chad", phoneCode: "+235" },
  { code: "CL", country: "Chile", phoneCode: "+56" },
  { code: "CN", country: "China", phoneCode: "+86" },
  { code: "CO", country: "Colombia", phoneCode: "+57" },
  { code: "KM", country: "Comoros", phoneCode: "+269" },
  { code: "CG", country: "Congo", phoneCode: "+242" },
  { code: "CD", country: "Congo (DRC)", phoneCode: "+243" },
  { code: "CR", country: "Costa Rica", phoneCode: "+506" },
  { code: "CI", country: "Côte d'Ivoire", phoneCode: "+225" },
  { code: "HR", country: "Croatia", phoneCode: "+385" },
  { code: "CU", country: "Cuba", phoneCode: "+53" },
  { code: "CY", country: "Cyprus", phoneCode: "+357" },
  { code: "CZ", country: "Czech Republic", phoneCode: "+420" },
  { code: "DK", country: "Denmark", phoneCode: "+45" },
  { code: "DJ", country: "Djibouti", phoneCode: "+253" },
  { code: "DM", country: "Dominica", phoneCode: "+1-767" },
  { code: "DO", country: "Dominican Republic", phoneCode: "+1-809" },
  { code: "EC", country: "Ecuador", phoneCode: "+593" },
  { code: "EG", country: "Egypt", phoneCode: "+20" },
  { code: "SV", country: "El Salvador", phoneCode: "+503" },
  { code: "GQ", country: "Equatorial Guinea", phoneCode: "+240" },
  { code: "ER", country: "Eritrea", phoneCode: "+291" },
  { code: "EE", country: "Estonia", phoneCode: "+372" },
  { code: "ET", country: "Ethiopia", phoneCode: "+251" },
  { code: "FJ", country: "Fiji", phoneCode: "+679" },
  { code: "FI", country: "Finland", phoneCode: "+358" },
  { code: "FR", country: "France", phoneCode: "+33" },
  { code: "GA", country: "Gabon", phoneCode: "+241" },
  { code: "GM", country: "Gambia", phoneCode: "+220" },
  { code: "DE", country: "Germany", phoneCode: "+49" },
  { code: "GH", country: "Ghana", phoneCode: "+233" },
  { code: "GR", country: "Greece", phoneCode: "+30" },
  { code: "GD", country: "Grenada", phoneCode: "+1-473" },
  { code: "GT", country: "Guatemala", phoneCode: "+502" },
  { code: "GN", country: "Guinea", phoneCode: "+224" },
  { code: "GW", country: "Guinea-Bissau", phoneCode: "+245" },
  { code: "GY", country: "Guyana", phoneCode: "+592" },
  { code: "HT", country: "Haiti", phoneCode: "+509" },
  { code: "HN", country: "Honduras", phoneCode: "+504" },
  { code: "HU", country: "Hungary", phoneCode: "+36" },
  { code: "IS", country: "Iceland", phoneCode: "+354" },
  { code: "IN", country: "India", phoneCode: "+91" },
  { code: "ID", country: "Indonesia", phoneCode: "+62" },
  { code: "IR", country: "Iran", phoneCode: "+98" },
  { code: "IQ", country: "Iraq", phoneCode: "+964" },
  { code: "IE", country: "Ireland", phoneCode: "+353" },
  { code: "IL", country: "Israel", phoneCode: "+972" },
  { code: "IT", country: "Italy", phoneCode: "+39" },
  { code: "JM", country: "Jamaica", phoneCode: "+1-876" },
  { code: "JP", country: "Japan", phoneCode: "+81" },
  { code: "JO", country: "Jordan", phoneCode: "+962" },
  { code: "KZ", country: "Kazakhstan", phoneCode: "+7" },
  { code: "KE", country: "Kenya", phoneCode: "+254" },
  { code: "KI", country: "Kiribati", phoneCode: "+686" },
  { code: "KR", country: "South Korea", phoneCode: "+82" },
  { code: "KW", country: "Kuwait", phoneCode: "+965" },
  { code: "KG", country: "Kyrgyzstan", phoneCode: "+996" },
  { code: "LA", country: "Laos", phoneCode: "+856" },
  { code: "LV", country: "Latvia", phoneCode: "+371" },
  { code: "LB", country: "Lebanon", phoneCode: "+961" },
  { code: "LS", country: "Lesotho", phoneCode: "+266" },
  { code: "LR", country: "Liberia", phoneCode: "+231" },
  { code: "LY", country: "Libya", phoneCode: "+218" },
  { code: "LI", country: "Liechtenstein", phoneCode: "+423" },
  { code: "LT", country: "Lithuania", phoneCode: "+370" },
  { code: "LU", country: "Luxembourg", phoneCode: "+352" },
  { code: "MG", country: "Madagascar", phoneCode: "+261" },
  { code: "MW", country: "Malawi", phoneCode: "+265" },
  { code: "MY", country: "Malaysia", phoneCode: "+60" },
  { code: "MV", country: "Maldives", phoneCode: "+960" },
  { code: "ML", country: "Mali", phoneCode: "+223" },
  { code: "MT", country: "Malta", phoneCode: "+356" },
  { code: "MH", country: "Marshall Islands", phoneCode: "+692" },
  { code: "MR", country: "Mauritania", phoneCode: "+222" },
  { code: "MU", country: "Mauritius", phoneCode: "+230" },
  { code: "MX", country: "Mexico", phoneCode: "+52" },
  { code: "FM", country: "Micronesia", phoneCode: "+691" },
  { code: "MD", country: "Moldova", phoneCode: "+373" },
  { code: "MC", country: "Monaco", phoneCode: "+377" },
  { code: "MN", country: "Mongolia", phoneCode: "+976" },
  { code: "ME", country: "Montenegro", phoneCode: "+382" },
  { code: "MA", country: "Morocco", phoneCode: "+212" },
  { code: "MZ", country: "Mozambique", phoneCode: "+258" },
  { code: "MM", country: "Myanmar", phoneCode: "+95" },
  { code: "NA", country: "Namibia", phoneCode: "+264" },
  { code: "NR", country: "Nauru", phoneCode: "+674" },
  { code: "NP", country: "Nepal", phoneCode: "+977" },
  { code: "NL", country: "Netherlands", phoneCode: "+31" },
  { code: "NZ", country: "New Zealand", phoneCode: "+64" },
  { code: "NI", country: "Nicaragua", phoneCode: "+505" },
  { code: "NE", country: "Niger", phoneCode: "+227" },
  { code: "NG", country: "Nigeria", phoneCode: "+234" },
  { code: "NO", country: "Norway", phoneCode: "+47" },
  { code: "OM", country: "Oman", phoneCode: "+968" },
  { code: "PK", country: "Pakistan", phoneCode: "+92" },
  { code: "PW", country: "Palau", phoneCode: "+680" },
  { code: "PS", country: "Palestine", phoneCode: "+970" },
  { code: "PA", country: "Panama", phoneCode: "+507" },
  { code: "PG", country: "Papua New Guinea", phoneCode: "+675" },
  { code: "PY", country: "Paraguay", phoneCode: "+595" },
  { code: "PE", country: "Peru", phoneCode: "+51" },
  { code: "PH", country: "Philippines", phoneCode: "+63" },
  { code: "PL", country: "Poland", phoneCode: "+48" },
  { code: "PT", country: "Portugal", phoneCode: "+351" },
  { code: "QA", country: "Qatar", phoneCode: "+974" },
  { code: "RO", country: "Romania", phoneCode: "+40" },
  { code: "RU", country: "Russia", phoneCode: "+7" },
  { code: "RW", country: "Rwanda", phoneCode: "+250" },
  { code: "WS", country: "Samoa", phoneCode: "+685" },
  { code: "SM", country: "San Marino", phoneCode: "+378" },
  { code: "ST", country: "Sao Tome and Principe", phoneCode: "+239" },
  { code: "SA", country: "Saudi Arabia", phoneCode: "+966" },
  { code: "SN", country: "Senegal", phoneCode: "+221" },
  { code: "RS", country: "Serbia", phoneCode: "+381" },
  { code: "SC", country: "Seychelles", phoneCode: "+248" },
  { code: "SL", country: "Sierra Leone", phoneCode: "+232" },
  { code: "SG", country: "Singapore", phoneCode: "+65" },
  { code: "SK", country: "Slovakia", phoneCode: "+421" },
  { code: "SI", country: "Slovenia", phoneCode: "+386" },
  { code: "SB", country: "Solomon Islands", phoneCode: "+677" },
  { code: "SO", country: "Somalia", phoneCode: "+252" },
  { code: "ZA", country: "South Africa", phoneCode: "+27" },
  { code: "ES", country: "Spain", phoneCode: "+34" },
  { code: "LK", country: "Sri Lanka", phoneCode: "+94" },
  { code: "SD", country: "Sudan", phoneCode: "+249" },
  { code: "SR", country: "Suriname", phoneCode: "+597" },
  { code: "SZ", country: "Swaziland", phoneCode: "+268" },
  { code: "SE", country: "Sweden", phoneCode: "+46" },
  { code: "CH", country: "Switzerland", phoneCode: "+41" },
  { code: "SY", country: "Syria", phoneCode: "+963" },
  { code: "TW", country: "Taiwan", phoneCode: "+886" },
  { code: "TJ", country: "Tajikistan", phoneCode: "+992" },
  { code: "TZ", country: "Tanzania", phoneCode: "+255" },
  { code: "TH", country: "Thailand", phoneCode: "+66" },
  { code: "TL", country: "Timor-Leste", phoneCode: "+670" },
  { code: "TG", country: "Togo", phoneCode: "+228" },
  { code: "TO", country: "Tonga", phoneCode: "+676" },
  { code: "TT", country: "Trinidad and Tobago", phoneCode: "+1-868" },
  { code: "TN", country: "Tunisia", phoneCode: "+216" },
  { code: "TR", country: "Turkey", phoneCode: "+90" },
  { code: "TM", country: "Turkmenistan", phoneCode: "+993" },
  { code: "TV", country: "Tuvalu", phoneCode: "+688" },
  { code: "UG", country: "Uganda", phoneCode: "+256" },
  { code: "UA", country: "Ukraine", phoneCode: "+380" },
  { code: "AE", country: "United Arab Emirates", phoneCode: "+971" },
  { code: "GB", country: "United Kingdom", phoneCode: "+44" },
  { code: "US", country: "United States", phoneCode: "+1" },
  { code: "UY", country: "Uruguay", phoneCode: "+598" },
  { code: "UZ", country: "Uzbekistan", phoneCode: "+998" },
  { code: "VU", country: "Vanuatu", phoneCode: "+678" },
  { code: "VA", country: "Vatican City", phoneCode: "+39-06" },
  { code: "VE", country: "Venezuela", phoneCode: "+58" },
  { code: "VN", country: "Vietnam", phoneCode: "+84" },
  { code: "YE", country: "Yemen", phoneCode: "+967" },
  { code: "ZM", country: "Zambia", phoneCode: "+260" },
  { code: "ZW", country: "Zimbabwe", phoneCode: "+263" },
];

